artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  dataset_id: waqi786/mental-health-and-technology-usage-dataset
  local_data_path: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_dir: artifacts/data_ingestion
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["mental_health_and_technology_usage_2024.csv"]
