artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://www.kaggle.com/api/v1/datasets/download/waqi786/mental-health-and-technology-usage-dataset?dataset_version_number=1
